---
abstract: 'PDL interface to the Fastest Fourier Transform in the West'
author:
  - 'Dima Kogan <dima@secretsauce.net>, Craig DeForest <deforest@boulder.swri.edu>'
build_requires:
  PDL::PP: 0
configure_requires:
  Alien::FFTW3: 0
  IPC::Run: 0
  PDL::Core::Dev: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-FFTW3
no_index:
  directory:
    - t
    - inc
provides:
  PDL::FFTW3:
    file: FFTW3.pd
    version: v0.2.2_2
requires:
  PDL: 2.001
resources:
  bugtracker: http://github.com/dkogan/PDL-FFTW3/issues
  homepage: http://github.com/dkogan/PDL-FFTW3
  repository: git://github.com/dkogan/PDL-FFTW3.git
version: v0.02.2_02
